export const Venues = [
    {
        id: '1',
        name: 'Espresso Lab',
        type: 'Cafe',
        area: 'Maadi',
        rating: 4.8,
        image: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?fit=crop&w=800&q=80',
        description: 'A cozy spot for coffee lovers with a great atmosphere for working.',
        location: 'Road 9, Maadi',
        moods: ['Work', 'Chill'],
    },
    {
        id: '2',
        name: 'Ovio',
        type: 'Restaurant',
        area: 'Zamalek',
        rating: 4.5,
        image: 'https://images.unsplash.com/photo-1559339352-11d035aa65de?fit=crop&w=800&q=80',
        description: 'European style restaurant serving breakfast, lunch and dinner.',
        location: 'Brazil St, Zamalek',
        moods: ['Date Night', 'Outing'],
    },
    {
        id: '3',
        name: 'Cake Cafe',
        type: 'Bakery',
        area: 'New Cairo',
        rating: 4.7,
        image: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?fit=crop&w=800&q=80',
        description: 'Delicious cakes and pastries in a vibrant setting.',
        location: 'Waterway 2, New Cairo',
        moods: ['Chill', 'Outing'],
    },
    {
        id: '4',
        name: 'Villa Belle Epoque',
        type: 'Hotel & Restaurant',
        area: 'Maadi',
        rating: 4.9,
        image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?fit=crop&w=800&q=80',
        description: 'Boutique hotel with a stunning garden restaurant.',
        location: 'Road 13, Maadi',
        moods: ['Date Night', 'Chill'],
    },
    {
        id: '5',
        name: 'Crimson',
        type: 'Rooftop',
        area: 'Zamalek',
        rating: 4.6,
        image: 'https://placehold.co/800x600/FF5F1F/ffffff?text=Crimson+Rooftop',
        description: 'Rooftop bar and grill with a view of the Nile.',
        location: 'Abu El Feda St, Zamalek',
        moods: ['Date Night', 'Outing'],
    },
];
